<?php

/**
 * @file
 * Contains opencase_defaults.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\Entity\Role;
use Drupal\user\RoleInterface;

/**
 * Implements hook_help().
 */
function opencase_defaults_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the opencase_defaults module.
    case 'help.page.opencase_defaults':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('OpenCase Default Configuration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function opencase_defaults_theme() {
  return [
    'opencase_defaults' => [
      'render element' => 'children',
    ],
  ];
}

