<?php

/**
 * @file
 * Contains opencase_reporting.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function opencase_reporting_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the opencase_reporting module.
    case 'help.page.opencase_reporting':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Reporting functionality for OpenCase.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments
 *
 * Add the opencase library to every page
 */
function opencase_reporting_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'opencase_reporting/opencase-reporting-lib';
}

/**
 * Implements hook_uninstall().
 * Removes configs.
 */
function opencase_reporting_uninstall() {
  $configs = [
    'search_api.server.opencase_reporting_server',
    'search_api.index.opencase_reporting_actors',
    'facets.facet.actor_type',
    'facets.facet.actor_type_export',
    'facets.facet.created',
    'facets.facet.created_export',
    'views.view.reporting_actors',
    'block.block.facet_actortype',
    'block.block.facet_created',
  ];
  foreach($configs as $config) {
    Drupal::configFactory()->getEditable($config)->delete();
  }
} 
