<?php

/**
 * @file
 * Contains opencase_search.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function opencase_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the opencase_search module.
    case 'help.page.opencase_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Search functionality for OpenCase') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function opencase_search_theme() {
  return [
    'opencase_search' => [
      'render element' => 'children',
    ],
  ];
}
