opencase_entities.oc_case_type.*:
  type: config_entity
  label: 'Case type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    allowedActivityTypes:
      type: sequence
      label: 'Allowed Activity Types'
    uuid:
      type: string
