<?php

/**
 * @file
 * Contains zencrm_entities.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_ENTITY_TYPE_presave().
 * Computes the full_name field from first_name middle_names and last_name.
 * Computes the first_and_last_name field from first_name and last_name.
 */
function zencrm_entities_person_presave($entity) {
  $first_name = $entity->first_name->getString(); 
  $middle_names = $entity->middle_names->getString();
  $last_name = $entity->last_name->getString();
  if ($middle_names) {
    $middle_names .= ' ';
  }
  $first_and_last_name = $first_name . ' ' . $last_name; 
  $full_name = $first_name . ' ' . $middle_names . $last_name;
  $entity->set('full_name', $full_name);
  $entity->set('first_and_last_name', $first_and_last_name);
} 


/**
 * Implements hook_ENTITY_TYPE_presave().
 * Computes the name field from the full name of the referenced person
 * plus the hat type.
 */
function zencrm_entities_hat_presave($entity) {
  $person_id =  $entity->person->first()->getValue()['target_id'];
  $person = \Drupal\zencrm_entities\Entity\Person::load($person_id);
  $full_name = $person->full_name->getString();
  $bundle_name = $entity->type->entity->label();
  $entity->set('name', $full_name . ' - ' . $bundle_name);
} 


/**
 * Implements hook_help().
 */
function zencrm_entities_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the zencrm_entities module.
    case 'help.page.zencrm_entities':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Zen CRM Entities') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function zencrm_entities_theme() {
  $theme = [];
  $theme['zencrm_entities'] = [
    'render element' => 'children',
  ];
  $theme['hat'] = [
    'render element' => 'elements',
    'file' => 'hat.page.inc',
    'template' => 'hat',
  ];
  $theme['hat_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'hat.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function zencrm_entities_theme_suggestions_hat(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#hat'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'hat__' . $sanitized_view_mode;
  $suggestions[] = 'hat__' . $entity->bundle();
  $suggestions[] = 'hat__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'hat__' . $entity->id();
  $suggestions[] = 'hat__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
